<?php

namespace Blinkin\BiBundle\Entity;

/**
 * TabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabRepository extends \Doctrine\ORM\EntityRepository
{
}
